---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          volumeMounts:
          - mountPath: /var/run/envoy-uds
            name: ext-auth-uds
        initContainers:
        - name: ext-auth-svc
          restartPolicy: Always
          command:
          - /ext-auth
          image: ghcr.io/tetratelabs/teg-ext-auth-poc:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /var/run/envoy-uds
            name: ext-auth-uds
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
        pod:
          volumes:
          - emptyDir: {}
            name: ext-auth-uds
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: ext-auth-svc
spec:
  endpoints:
  - unix:
      path: /var/run/envoy-uds/ext-auth.sock
