name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  docker_images:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build and Push Image
        run: |
          make push-image
